
# ========== 共通設定 ==========
# 連携用ファイルの保存先ディレクトリ
# ※連携先サーバーからアクセスするため、絶対パスでの記載を推奨
sync-data-dir: ""

# 処理失敗時の退避先サーバー
escape-server: ""

# 通貨報酬の実行コマンド
# ※<player>: プレイヤー名、<amount>: 金額
balance-reward-command: "essentials:eco give <player> <amount>"


# ========== 各サーバー設定 ==========
# サーバーのインベントリデータを原本とするか
# ※true: 連携元サーバー
#   ・連携先サーバーにコピーするインベントリデータを作成する
#   ・ログイン時に報酬データの受取を行う
# ※false: 連携先サーバー
#   ・連携元サーバーからインベントリデータをコピーする
#   ・報酬データのコンフィグファイルを連携元サーバーと同期する
original: true

# 報酬情報の自動保存間隔(単位：秒)
# ※ゲーム内で配布された報酬情報は一時的にメモリに保存され、
#   一定の間隔でファイルに記録されます。
#   この設定は連携先サーバーでのみ有効です。
reward-save-interval: 60

# インベントリ読み込みタイムアウト時間(単位：秒)
# ※連携元サーバーからインベントリデータを取得する際のタイムアウト時間
#   この設定は連携先サーバーでのみ有効です。
#   タイムアウトした場合、「処理失敗時の退避先サーバー」に移動します。
inventory-load-timeout: 3
